#!/bin/bash
# Code by Jioh L. Jung (ziozzang@gmail.com)

NETNS=/var/run/netns
mkdir -p ${NETNS}

# Acquire docker ids. (don't need -a option. fixed)
p=`docker inspect --format {{.Config.Hostname}} ${1}`
pid=`docker inspect --format {{.State.Pid}} ${p}`
# pid must not 0
if [ "$pid" -ne "0" ]; then
  # Create Link if not exist
  if [ ! -e "${NETNS}/${p}" ]; then
   ln -s /proc/${pid}/ns/net ${NETNS}/${p}
  fi
fi
