#!/bin/bash
STAT_FILE=/var/run/docker-ovs-ip
function failed()
{
  echo "Run Command Like This."
  echo "> $0 bridge_name [container_ID]"
  echo "> $0 br0 UUID"
  exit 1
}

# Get Params
if [ -z "$2" ]; then
  echo "No argument supplied"
  failed
fi

BRG=${BRG:-"$1"}
CID=${CID:-"$2"}

HS=`docker inspect --format {{.Config.Hostname}} ${CID}`
if [ ! -f ${STAT_FILE} ]; then
  touch ${STAT_FILE}
fi
cat ${STAT_FILE} | grep -v "${HS}"  > ${STAT_FILE}
HS=${HS:0:5}
ip link set ${HS}-${BRG} down
ip netns exec ${HS} ip link set eth0 down
ovs-vsctl del-port ${BRG} ${HS}-${BRG}
ip link del ${HS}-${BRG} type veth peer name ${HS}.${BRG}

