#!/bin/bash
STAT_FILE=/var/run/docker-ovs-ip
function failed()
{
  echo "Run Command Like This."
  echo "> $0 bridge_name [container_ID] [ethXname]"
  echo "> $0 br0 UUID eth1"
  exit 1
}

# Get Params
if [ -z "$2" ]; then
  echo "No argument supplied"
  failed
fi

BRG=${BRG:-"$1"}
CID=${CID:-"$2"}
NIC=${3:-"eth0"}

HS=`docker inspect --format {{.Config.Hostname}} ${CID}`
if [ ! -f ${STAT_FILE} ]; then
  touch ${STAT_FILE}
fi
cat ${STAT_FILE} | grep -v "${HS}"  > ${STAT_FILE}
HM=${HS:0:5}
ip link set ${HM}-${BRG} down
ip netns exec ${HS} ip link set ${NIC} down
brctl delif ${BRG} ${HM}-${BRG}
ip link del ${HM}-${BRG} type veth peer name ${HM}.${BRG}

