#!/bin/bash
# Code by Jioh L. Jung (ziozzang@gmail.com)

NETNS=/var/run/netns
mkdir -p ${NETNS}

# Acquire docker ids. (don't need -a option. fixed)
p=`docker inspect --format {{.Config.Hostname}} ${1}`
if [ -L "$f" ] ; then
  rm -f ${NETNS}/${p}
fi
